on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [web, worker]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
        working-directory: ./${{ matrix.service }}
      - run: npm test
        working-directory: ./${{ matrix.service }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm install
        working-directory: ./web
      - run: npm install
        working-directory: ./worker
      - run: npm run lint
